import AppKit
import Combine
import Foundation
import UniformTypeIdentifiers

struct IgnoredClipboardApplication: Codable, Equatable, Identifiable, Sendable {
    var id: String { bundleIdentifier }

    let bundleIdentifier: String
    let name: String
    let bundlePath: String?
}

enum PasswordManagerCatalog {
    struct Entry: Identifiable, Equatable, Sendable {
        let id: String
        let displayName: String
        let bundleIdentifiers: Set<String>
    }

    static let entries: [Entry] = [
        Entry(
            id: "1password",
            displayName: "1Password",
            bundleIdentifiers: [
                "com.1password.1password",
                "com.agilebits.onepassword7",
                "com.agilebits.onepassword4"
            ]
        ),
        Entry(
            id: "bitwarden",
            displayName: "Bitwarden",
            bundleIdentifiers: ["com.bitwarden.desktop"]
        ),
        Entry(
            id: "keepassxc",
            displayName: "KeePassXC",
            bundleIdentifiers: ["org.keepassxc.keepassxc"]
        ),
        Entry(
            id: "enpass",
            displayName: "Enpass",
            bundleIdentifiers: ["in.sinew.Enpass-Desktop"]
        ),
        Entry(
            id: "strongbox",
            displayName: "Strongbox",
            bundleIdentifiers: [
                "com.markmcguill.strongbox",
                "com.markmcguill.strongbox.mac"
            ]
        ),
        Entry(
            id: "nordpass",
            displayName: "NordPass",
            bundleIdentifiers: [
                "com.nordsec.nordpass",
                "com.nordvpn.macos.nordpass"
            ]
        ),
        Entry(
            id: "proton-pass",
            displayName: "Proton Pass",
            bundleIdentifiers: [
                "me.proton.pass",
                "ch.protonmail.protonpass"
            ]
        )
    ]
}

struct ClipboardCapturePolicy: Equatable, Sendable {
    static let sensitiveTypeIdentifiers: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]
    static let remoteClipboardTypeIdentifier = "com.apple.is-remote-clipboard"

    let capturesUniversalClipboard: Bool
    let ignoredBundleIdentifiers: Set<String>
    let invokerBundleIdentifier: String?

    func shouldIgnore(
        typeIdentifiers: Set<String>,
        sourceApplication: ClipboardSourceApplication?
    ) -> Bool {
        if !typeIdentifiers.isDisjoint(with: Self.sensitiveTypeIdentifiers) {
            return true
        }
        if !capturesUniversalClipboard,
           typeIdentifiers.contains(Self.remoteClipboardTypeIdentifier) {
            return true
        }
        guard let bundleIdentifier = sourceApplication?.bundleIdentifier else {
            return false
        }
        if bundleIdentifier == invokerBundleIdentifier {
            return true
        }
        return ignoredBundleIdentifiers.contains(bundleIdentifier)
    }
}

private enum ClipboardHistoryDefaultsKey {
    static let capturesUniversalClipboard = "clipboardHistory.capturesUniversalClipboard"
    static let maxHistoryItems = "clipboardHistory.maxItems"
    static let maxStorageMegabytes = "clipboardHistory.maxStorageMegabytes"
    static let disabledPasswordManagers = "clipboardHistory.disabledPasswordManagers"
    static let ignoredApplications = "clipboardHistory.ignoredApplications"
}

@MainActor
final class ClipboardHistorySettingsStore: ObservableObject {
    static let defaultMaxHistoryItems = 200
    static let defaultMaxStorageMegabytes = 100
    static let maxPinnedItems = 50
    static let maxSingleItemBytes = 10 * 1_024 * 1_024

    @Published var capturesUniversalClipboard: Bool {
        didSet {
            userDefaults.set(
                capturesUniversalClipboard,
                forKey: ClipboardHistoryDefaultsKey.capturesUniversalClipboard
            )
        }
    }

    @Published var maxHistoryItems: Int {
        didSet {
            userDefaults.set(maxHistoryItems, forKey: ClipboardHistoryDefaultsKey.maxHistoryItems)
        }
    }

    @Published var maxStorageMegabytes: Int {
        didSet {
            userDefaults.set(
                maxStorageMegabytes,
                forKey: ClipboardHistoryDefaultsKey.maxStorageMegabytes
            )
        }
    }

    @Published private(set) var disabledPasswordManagerIDs: Set<String> {
        didSet {
            userDefaults.set(
                Array(disabledPasswordManagerIDs).sorted(),
                forKey: ClipboardHistoryDefaultsKey.disabledPasswordManagers
            )
        }
    }

    @Published private(set) var ignoredApplications: [IgnoredClipboardApplication] {
        didSet {
            if let data = try? JSONEncoder().encode(ignoredApplications) {
                userDefaults.set(data, forKey: ClipboardHistoryDefaultsKey.ignoredApplications)
            }
        }
    }

    private let userDefaults: UserDefaults

    init(userDefaults: UserDefaults = .standard) {
        self.userDefaults = userDefaults
        capturesUniversalClipboard = userDefaults.bool(
            forKey: ClipboardHistoryDefaultsKey.capturesUniversalClipboard
        )

        let storedMaxItems = userDefaults.integer(forKey: ClipboardHistoryDefaultsKey.maxHistoryItems)
        maxHistoryItems = storedMaxItems > 0 ? storedMaxItems : Self.defaultMaxHistoryItems

        let storedStorageLimit = userDefaults.integer(
            forKey: ClipboardHistoryDefaultsKey.maxStorageMegabytes
        )
        maxStorageMegabytes = storedStorageLimit > 0
            ? storedStorageLimit
            : Self.defaultMaxStorageMegabytes

        disabledPasswordManagerIDs = Set(
            userDefaults.stringArray(forKey: ClipboardHistoryDefaultsKey.disabledPasswordManagers)
                ?? []
        )

        if let data = userDefaults.data(forKey: ClipboardHistoryDefaultsKey.ignoredApplications),
           let applications = try? JSONDecoder().decode(
               [IgnoredClipboardApplication].self,
               from: data
           ) {
            ignoredApplications = applications
        } else {
            ignoredApplications = []
        }
    }

    var maxStorageBytes: Int {
        maxStorageMegabytes * 1_024 * 1_024
    }

    var capturePolicy: ClipboardCapturePolicy {
        var ignoredBundleIdentifiers = Set(ignoredApplications.map(\.bundleIdentifier))
        for entry in PasswordManagerCatalog.entries
            where !disabledPasswordManagerIDs.contains(entry.id) {
            ignoredBundleIdentifiers.formUnion(entry.bundleIdentifiers)
        }
        return ClipboardCapturePolicy(
            capturesUniversalClipboard: capturesUniversalClipboard,
            ignoredBundleIdentifiers: ignoredBundleIdentifiers,
            invokerBundleIdentifier: Bundle.main.bundleIdentifier
        )
    }

    func isPasswordManagerEnabled(_ entry: PasswordManagerCatalog.Entry) -> Bool {
        !disabledPasswordManagerIDs.contains(entry.id)
    }

    func setPasswordManager(_ entry: PasswordManagerCatalog.Entry, enabled: Bool) {
        if enabled {
            disabledPasswordManagerIDs.remove(entry.id)
        } else {
            disabledPasswordManagerIDs.insert(entry.id)
        }
    }

    func addIgnoredApplication() {
        let panel = NSOpenPanel()
        panel.title = "选择不记录剪贴板的应用"
        panel.prompt = "忽略此应用"
        panel.allowsMultipleSelection = false
        panel.canChooseDirectories = false
        panel.canChooseFiles = true
        panel.allowedContentTypes = [.application]

        guard panel.runModal() == .OK,
              let applicationURL = panel.url,
              let bundle = Bundle(url: applicationURL),
              let bundleIdentifier = bundle.bundleIdentifier
        else {
            return
        }

        let name = bundle.object(forInfoDictionaryKey: "CFBundleDisplayName") as? String
            ?? bundle.object(forInfoDictionaryKey: "CFBundleName") as? String
            ?? applicationURL.deletingPathExtension().lastPathComponent
        addIgnoredApplication(
            IgnoredClipboardApplication(
                bundleIdentifier: bundleIdentifier,
                name: name,
                bundlePath: applicationURL.path
            )
        )
    }

    func addIgnoredApplication(_ application: IgnoredClipboardApplication) {
        let bundleIdentifier = application.bundleIdentifier
        ignoredApplications.removeAll { $0.bundleIdentifier == bundleIdentifier }
        ignoredApplications.append(application)
        ignoredApplications.sort { $0.name.localizedStandardCompare($1.name) == .orderedAscending }
    }

    func removeIgnoredApplication(_ application: IgnoredClipboardApplication) {
        ignoredApplications.removeAll { $0.bundleIdentifier == application.bundleIdentifier }
    }
}
